# Generated by Django 2.2.3 on 2020-03-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infosys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infosys.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infosys.Student')),
            ],
            options={
                'verbose_name': 'representative',
                'verbose_name_plural': 'representative',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infosys.Student')),
            ],
            options={
                'verbose_name': '学生事件',
                'verbose_name_plural': '学生事件',
            },
        ),
    ]
